### ISSUE TITLE
Password fields characters - Login and Register forms

### ISSUE THREAD

**Issue by antoniaat** [antoniaat/Invoice-App#1]
Make password fields to be characters (*****) in **Login** and **Register** form.

Expected Behaviour:
![image](https://user-images.githubusercontent.com/20865548/78452442-eefc3e80-7693-11ea-8e8e-de1235402b35.png)

Actual Behaviour:
![image](https://user-images.githubusercontent.com/20865548/78452390-b5c3ce80-7693-11ea-988b-68bb020f60d3.png)

**Comment by iliyanstoyanov** [comment]
Fixed the symbols in the password field to be characters in Login and Register forms.
