### ISSUE TITLE
Style Invoice List Form

### ISSUE THREAD

**Issue by antoniaat** [antoniaat/Invoice-App#3]
![image](https://user-images.githubusercontent.com/20865548/78457847-f03e6300-76b5-11ea-97cd-c62cc4a8bfc0.png)

**Comment by Svetliovr** [comment]
Style invoice form design done 
![1](https://user-images.githubusercontent.com/30407630/78502088-ebd28280-7767-11ea-8090-eae4b8a695fb.png)
