### ISSUE TITLE
Back button link in my company form

### ISSUE THREAD

**Issue by antoniaat** [antoniaat/Invoice-App#4]
The back button link in my company form doesn't redirect to the home navigation form.
![image](https://user-images.githubusercontent.com/20865548/78458139-c5eda500-76b7-11ea-9868-566f74a1c2a4.png)

**Comment by iliyanstoyanov** [comment]
Fixed the back button to redirect us to the home navigation form by adding the code:

"this.Hide();
            StartPage startPageForm  = new StartPage();
            startPageForm.ShowDialog();
            this.Close();"
